### PR TITLE
Bot API 7.2

### PR DESCRIPTION
**Pull request by literallyfiro**

### CODE REVIEW

**Comment by literallyfiro** [comment]
> Mixed-Format Sticker Packs
> 
>     Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
>     Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
>     Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
>     Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).
>     Increased the maximum number of stickers in any regular and mask sticker set to 120.
>     Allowed to upload WEBM stickers using [SendSticker](https://core.telegram.org/bots/api#sendsticker).

Sticker packs are partially missing. Planning to implement them in a future PR

> Added the field BiometricManager to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).

WebApps are totally missing.

At this point I think this PR is good to go. Waiting for review

**Review by Stredox02 — COMMENTED** [review]
Everything is fine but why @Range is commented?

**Comment by literallyfiro** [comment]
> Everything is fine but why @range is commented?

> opening_minute 	Integer 	The minute's sequence number in a week, starting on Monday, marking the start of the time interval during which the business is open; 0 - 7 24 60
> closing_minute 	Integer 	The minute's sequence number in a week, starting on Monday, marking the end of the time interval during which the business is open; 0 - 8 24 60

Honestly this part doesn't make sense to me, that's why it's commented

**Comment by Stredox02** [comment]
Alright

**Review by Stredox02 — APPROVED** [review]

**Pull request merged**
