### PR TITLE
Remove static library initializer

### PR DESCRIPTION
**Pull request by literallyfiro**
### Breaking change!

I feel like the TeleightBots#init method is just redundant and could be changed with a simpler static initializer. Developers don't need to init and start the library anymore - that is now automated

The start method was also pretty much redundant since the only thing it did was to create a shutdown hook. That could be easily implemented inside the `TeleightBotsProcessImpl` constructor

### CODE REVIEW

**Comment by Stredox02** [comment]
I think it would be better if the developer chooses when to initialize the library so that it is 100% customizable.

**Comment by literallyfiro** [comment]
> I think it would be better if the developer chooses when to initialize the library so that it is 100% customizable.

Since this PR uses a java static initializer, the bots process will be initialized only when the Teleight class actually gets loaded (e.g. by calling another static method in the class). And if you need to load the Teleight class, that means you actually want to utilize the library

**Comment by Stredox02** [comment]
Fair enough let's try this different approach

**Comment by Stredox02** [comment]
> > I think it would be better if the developer chooses when to initialize the library so that it is 100% customizable.
> 
> Since this PR uses a java static initializer, the bots process will be initialized only when the Teleight class actually gets loaded (e.g. by calling another static method in the class). And if you need to load the Teleight class, that means you actually want to utilize the library

Fair enough let's try this different approach

**Review by Stredox02 — APPROVED** [review]

**Comment by Stredox02** [comment]
Just need to update the master branch

**Pull request merged**
